name: lot-systems-dev
# Force rebuild timestamp: $(date +%s)
region: nyc3
services:
  - name: web
    git:
      branch: master
      repo_clone_url: https://github.com/vadikmarmeladov/lot-systems.git
    build_command: |
      echo "Git commit being built:"
      git rev-parse HEAD
      
      echo "Starting build process..."
      # Rest of your build command...
