name: lot-systems-dev
region: nyc3
services:
  - name: web
    git:
      branch: master
      repo_clone_url: https://github.com/vadikmarmeladov/lot-systems.git
    build_command: |
      echo "🚀 Build started at $(date)"
      
      # Install dependencies
      echo "📦 Installing dependencies..."
      yarn install --frozen-lockfile --production=false || {
        echo "❌ Dependency installation failed"
        exit 1
      }
      
      # Create build directories
      echo "📁 Creating build directories..."
      mkdir -p dist/client/{css,js} dist/server/server
      
      # Build process
      echo "🛠 Starting build process..."
      
      # Build server
      echo "🔧 Building server..."
      NODE_ENV=production yarn run server:build || {
        echo "❌ Server build failed"
        exit 1
      }
      
      # Verify server build output and handle different file extensions
      if [ -f "dist/server/server/index.mjs" ]; then
        echo "📝 Converting MJS to JS..."
        mv dist/server/server/index.mjs dist/server/server/index.js
      fi
      
      # Build client
      echo "🔧 Building client..."
      NODE_ENV=production yarn run client:css:build || {
        echo "❌ CSS build failed"
        exit 1
      }
      NODE_ENV=production yarn run client:js:build || {
        echo "❌ JS build failed"
        exit 1
      }
      
      # Final verification
      if [ ! -f "dist/server/server/index.js" ]; then
        echo "❌ Server build output missing"
        exit 1
      fi
      
      # Run migrations
      echo "🔄 Running migrations..."
      NODE_ENV=production yarn run migrations:up || {
        echo "❌ Migrations failed"
        exit 1
      }
      
      echo "✅ Build completed successfully at $(date)"
    run_command: node dist/server/server/index.js
    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: "postgresql://doadmin:AVNS_8V6Hqzuxwj0JkMxgNvR@db-postgresql-nyc3-92053-do-user-22640384-0.f.db.ondigitalocean.com:25060/defaultdb?sslmode=require"
      - key: PORT
        scope: RUN_TIME
        value: "8080"
      - key: APP_NAME
        scope: RUN_TIME
        value: "LOT Systems"
      - key: APP_HOST
        scope: RUN_TIME
        value: "${_self.PUBLIC_URL}"
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET # Added type for security
        value: "13919320b2a8816ced947b7a6385811b"
      - key: RESEND_API_KEY
        scope: RUN_TIME
        type: SECRET # Added type for security
        value: "re_83s23f6W_LbDfdmmXpXJ4je4i2kt1HA7u"
      - key: RESEND_FROM_EMAIL
        scope: RUN_TIME
        value: "support@lot-systems.com"
      - key: RESEND_FROM_NAME
        scope: RUN_TIME
        value: "LOT Systems"
      - key: BUILD_TIME
        scope: BUILD_TIME
        value: "${COMMIT_SHA}-${TIMESTAMP}"