cat << 'EOF' > app.yaml
name: lot-systems-dev
region: nyc3
services:
  - name: web
    git:
      branch: master
      repo_clone_url: https://github.com/vadikmarmeladov/lot-systems.git
    build_command: |
      echo "Starting build process..."
      
      # Create necessary directories
      mkdir -p dist/client/css dist/server
      
      # Install all required dependencies
      echo "Installing dependencies..."
      yarn add -D postcss-import
      yarn add -D tailwindcss@latest postcss@latest autoprefixer@latest
      yarn add -D postcss-nesting
      yarn add -D @tailwindcss/nesting
      yarn add -D esbuild
      yarn add -D vite
      yarn install --frozen-lockfile --production=false || exit 1
      
      # Install global packages
      echo "Installing global packages..."
      yarn global add postcss-cli esbuild-runner typescript-esbuild || exit 1
      
      # Debug configurations and structure
      echo "Current directory structure:"
      ls -la
      
      echo "PostCSS configuration:"
      cat postcss.config.js
      
      echo "Tailwind configuration:"
      cat tailwind.config.js
      
      # Build steps
      echo "Building client CSS..."
      NODE_ENV=production yarn run client:css:build || exit 1
      
      echo "Building client JS..."
      NODE_ENV=production yarn run client:js:build || exit 1
      
      echo "Building server..."
      NODE_ENV=production yarn run server:build || exit 1
      
      # Verify build outputs
      echo "Verifying build outputs..."
      ls -la dist/client/css/
      ls -la dist/server/
      
      # Run migrations
      echo "Running migrations..."
      NODE_ENV=production DATABASE_URL="postgresql://doadmin:AVNS_8V6Hqzuxwj0JkMxgNvR@db-postgresql-nyc3-92053-do-user-22640384-0.f.db.ondigitalocean.com:25060/defaultdb?sslmode=require" yarn run migrations:up || exit 1
      
      echo "Build process completed successfully"
    run_command: yarn run server:start
    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: "postgresql://doadmin:AVNS_8V6Hqzuxwj0JkMxgNvR@db-postgresql-nyc3-92053-do-user-22640384-0.f.db.ondigitalocean.com:25060/defaultdb?sslmode=require"
      - key: PORT
        scope: RUN_TIME
        value: "8080"
      - key: APP_NAME
        scope: RUN_TIME
        value: "LOT Systems"
      - key: APP_HOST
        scope: RUN_TIME
        value: "${_self.PUBLIC_URL}"
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        value: "13919320b2a8816ced947b7a6385811b"
      - key: RESEND_API_KEY
        scope: RUN_TIME
        value: "re_83s23f6W_LbDfdmmXpXJ4je4i2kt1HA7u"
      - key: RESEND_FROM_EMAIL
        scope: RUN_TIME
        value: "support@lot-systems.com"
      - key: RESEND_FROM_NAME
        scope: RUN_TIME
        value: "LOT Systems"
EOF