name: lot-systems-dev
region: nyc3
services:
  - name: web
    git:
      branch: master
      repo_clone_url: https://github.com/vadikmarmeladov/lot-systems.git
    build_command: |
      echo "Starting build process..."
      
      # Install dependencies
      echo "Installing dependencies..."
      yarn install --legacy-peer-deps || exit 1
      
      # Install global packages
      echo "Installing global packages..."
      yarn global add postcss-cli esbuild-runner typescript-esbuild || exit 1
      
      # Build client CSS
      echo "Building client CSS..."
      yarn run client:css:build || exit 1
      
      # Build client JS
      echo "Building client JS..."
      yarn run client:js:build || exit 1
      
      # Build server
      echo "Building server..."
      yarn run server:build || exit 1
      
      # Run migrations
      echo "Running migrations..."
      export DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require"
      echo "Database URL constructed (masked for security)"
      NODE_ENV=production yarn run migrations:up || exit 1
      
      echo "Build process completed successfully"
    run_command: yarn run server:start
    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: DB_USER
        scope: RUN_AND_BUILD_TIME
        value: "doadmin"
      - key: DB_PASSWORD
        scope: RUN_AND_BUILD_TIME
        value: "AVNS_8V6Hqzuxwj0JkMxgNvR"
      - key: DB_HOST
        scope: RUN_AND_BUILD_TIME
        value: "db-postgresql-nyc3-92053-do-user-22640384-0.f.db.ondigitalocean.com"
      - key: DB_PORT
        scope: RUN_AND_BUILD_TIME
        value: "25060"
      - key: DB_NAME
        scope: RUN_AND_BUILD_TIME
        value: "defaultdb"
      - key: DB_SSL
        scope: RUN_AND_BUILD_TIME
        value: "true"
      - key: PORT
        scope: RUN_TIME
        value: "8080"
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: "postgresql://doadmin:AVNS_8V6Hqzuxwj0JkMxgNvR@db-postgresql-nyc3-92053-do-user-22640384-0.f.db.ondigitalocean.com:25060/defaultdb?sslmode=require"
      - key: APP_NAME
        scope: RUN_TIME
        value: "LOT Systems"
      - key: APP_HOST
        scope: RUN_TIME
        value: "${_self.PUBLIC_URL}"
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        value: "13919320b2a8816ced947b7a6385811b"
      - key: RESEND_API_KEY
        scope: RUN_TIME
        value: "re_83s23f6W_LbDfdmmXpXJ4je4i2kt1HA7u"
      - key: RESEND_FROM_EMAIL
        scope: RUN_TIME
        value: "support@lot-systems.com"
      - key: RESEND_FROM_NAME
        scope: RUN_TIME
        value: "LOT Systems"